version: '3.8'
services:
  mek-db:
    image: postgres:latest
    container_name: mek-postgres-container
    environment:
      POSTGRES_USER: mekuser
      POSTGRES_PASSWORD: secret-mek-password
      POSTGRES_DB: mekdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: local-mek-db
