/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.kotlin-library-conventions")
    alias(libs.plugins.openapi)
}

dependencies {
    api(enforcedPlatform(libs.spring.boot.dependencies))

    implementation(libs.spring.boot.starter.web)
    implementation(libs.spring.boot.validation)
    implementation(libs.spring.boot.security)
    implementation(libs.spring.boot.starter.test)

    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0")

    implementation(project(":auth"))
    implementation(project(":iam"))
}

openApiGenerate {
    generatorName.set("kotlin-spring")
    inputSpec.set("${project.projectDir}/src/main/resources/api/v1/spec.yaml")
    configOptions.putAll(
        mapOf(
            Pair("gradleBuildFile", "false"),
            Pair("useSpringBoot3", "true"),
            Pair("documentationProvider", "none")
        )
    )
    generateApiTests.set(false)

    apiPackage.set("rest.api.v1")
    modelPackage.set("rest.api.v1")
}

tasks.compileKotlin {
    dependsOn(tasks.openApiGenerate)
}

sourceSets {
    main {
        java {
            srcDir("${layout.buildDirectory.get()}/generate-resources/main/src/main/kotlin")
        }
    }
}
