/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    api(enforcedPlatform(libs.spring.boot.dependencies))

    implementation(libs.spring.boot.starter.web)
    implementation(libs.spring.boot.starter.test)
    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.spring.boot.openapi)
    implementation(libs.spring.boot.security)
    implementation(libs.spring.boot.validation)

    implementation("org.apache.commons:commons-text")
    api(project(":auth"))
    api(project(":iam"))
}

application {
    mainClass = "mek.backend.app.ServiceApiApp"
}

openApiGenerate {
    generatorName.set("kotlin-spring")
    inputSpec.set("${project.projectDir}/src/main/resources/api/v1/spec.yaml")
    apiPackage.set("mek.backend.app")
    configOptions.putAll(
        mapOf(
            Pair("gradleBuildFile", "false"),
            Pair("useSpringBoot3", "true"),
            Pair("documentationProvider", "none"),
        )
    )
    generateApiTests.set(false)
}

tasks.compileKotlin {
    dependsOn(tasks.openApiGenerate)
}

sourceSets.getByName("main").kotlin.srcDir("${layout.buildDirectory}/generate-resources")
tasks.compileKotlin.get().dependsOn(tasks.openApiGenerate)