/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    api(enforcedPlatform(libs.spring.boot.dependencies))

    implementation(libs.spring.boot.starter.web)
    implementation(libs.spring.boot.starter.test)
    implementation(libs.spring.boot.openapi)
    implementation(libs.spring.boot.security)
    implementation(libs.spring.boot.validation)

    implementation("org.apache.commons:commons-text")
    implementation(project(":auth"))
}

application {
    // Define the main class for the application.
    mainClass = "mek.backend.app.ServiceApiApp"
}
