/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.kotlin-library-conventions")
}

dependencies {
    api(enforcedPlatform(libs.spring.boot.dependencies))

    implementation(libs.spring.boot.starter.data.jpa)
    implementation(libs.spring.boot.starter.test)

    implementation(libs.postgresql.jdbc)

    api(project(":auth"))
}