spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/mekdb
    password: secret-mek-password
    username: mekuser
    hikari:
      connection-timeout: 60000
      validation-timeout: 10000
      max-lifetime: 30000

      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 30000
      keepalive-time: 30000


springdoc:
  api-docs:
    enabled: true
  show-actuator: true