/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation(libs.spring.boot.starter.test)
    implementation(libs.spring.boot.starter.jdbc)
    implementation(libs.liquibase.core)

    api(enforcedPlatform(libs.spring.boot.dependencies))

    runtimeOnly(libs.postgresql.jdbc)
}

application {
    // Define the main class for the application.
    mainClass = "mek.backend.migrator.MigratorApp"
}
